### ISSUE TITLE
Flightpanel Switch Description not updating

### ISSUE THREAD

**Issue by scotflieger** [DCS-Skunkworks/DCSFlightpanels#83] opened 2020-06-10 09:31 UTC
When an switch action is edited (Edit DCS-BIOS Control)  and the Description changed (eg. Strobe to Strobe ON) the change is not saved to the .bindings file or displayed on FlightPanels PZ55 display.

**Comment by jdahlblom** [comment] 2020-06-13 16:29
I can't reproduce this? The description is saved and loaded. Tested on PZ55, version 4.0.75.

**Comment by scotflieger** [comment] 2020-06-14 07:56
The issue relates to a profile where there are 2 entries for the same switch. For example, attached is a F/A-18C I downloaded from DCS-FlightPanels-Profiles and modified for my own use. If I try to edit the Avionics Master on/off (that shows Gain Switch OVR/NORM for the first entry in the .bindings file) and change the description to Rdr ON (fir the second entry) then neither the Description on screen nor the descriptions in the .profile change. I am only trying to edit the Description and not the assigned DCS-BIOS function. I hope that helps. I have updated to 4.0.75.

**Comment by jdahlblom** [comment] 2020-06-18 15:10
Which description is it you are referring to? The "BATT ON" or the others?
![2020-06-18_180908](https://user-images.githubusercontent.com/10453261/85038120-e2fe2400-b18e-11ea-818e-93f76e8f752f.png)

**Comment by jdahlblom** [comment] 2020-06-18 15:21
Hmm, I can't reproduce that. How on earth?

**Comment by scotflieger** [comment] 2020-06-18 15:26
The main issue was with the ECM operation using the engine start switch. I had to manually edit the source file to get what I wanted. It appeared that the first entry for the switch in the .bindings file took priority over what appeared in the FlightPanels window.

**Comment by WarLord211** [comment] 2020-07-11 10:18
Duplicate of #78

**Comment by WarLord211** [comment] 2020-07-11 10:20
Duplicate of #78

**Comment by jdahlblom** [comment] 2020-07-25 07:15
@WarLord211 can you confirm this bug?

**Comment by WarLord211** [comment] 2020-07-31 11:30
its solved in 4.1.12

**Closed as completed** 2020-07-31 11:30 UTC
Labels: duplicate
