### ISSUE TITLE
F18 radio panel issue 

### ISSUE THREAD

**Issue by Nishizawa145** [DCS-Skunkworks/DCSFlightpanels#75] opened 2020-05-25 13:31 UTC
I have this issue with f18 radio panel. 
Com 1 and 2 volume knob is working but larger knob which should change chanel doesn't. Com frequency is shown correctly but only when I put it in cockpit.
Also ILS chanel after changing to manual is working weird.
It doesn't change chanel to the one I choose.
When I choose for example chanel 11 it is going to change to eg. 4 by its own.
No possibility to enter correct chanel.

**Comment by WarLord211** [comment] 2020-05-25 15:20
BIOS Side i cant see an problem. (tested the Switches)
Must be the interaction with Flightpanels

**Comment by jdahlblom** [comment] 2020-05-25 17:31
Unfortunately that is an airplane module I don't have.

**Comment by CrypticVillain** [comment] 2020-07-09 16:47
Not just this radio but all pre built radio panels do not work properly. Only radio panels with bindings set from scratch work correctly.

**Comment by Kurothas** [comment] 2020-08-08 17:26
Yeah got the same issue with all Modules, it is not related to the F-18 alone. A fix would be very appreciated :). Just bought the Radio only beacause i read it was supported by FlightPanels for DCS.

**Comment by WarLord211** [comment] 2020-08-09 07:50
predefined Radio Panels works well with last version. Testet A-10C, F5 and F14.

the predefined for F-18 not possible because F-18 module is missing for jdahlblom

**Comment by jdahlblom** [comment] 2020-08-09 08:54
Same issue with ALL modules?
> 
> 
> Yeah got the same issue with all Modules, it is not related to the F-18 alone. A fix would be very appreciated :). Just bought the Radio only beacause i read it was supported by FlightPanels for DCS.

**Comment by Kurothas** [comment] 2020-08-09 15:54
> Same issue with ALL modules?

Yes with DCSFlightpanels V4.1.12 basically the whole panel was not working with predefined radio anymore, doesn´t matter what plane has been used. Done a rollback to 4.0.76.7111 and it was working again. 

I´ll have a look to test the latest version. Probably need to update DCS-bios as well

**Comment by Kurothas** [comment] 2020-08-09 16:20
Ok, 
just updated DCSFlightPanels again to 4.1.12.3909 and updated DCS-bios to the latest release as well. 
F-18C: you can see the radio frequenz on the panel, you can change volume, you can push the radio buttons. Changing the frequency with the panel is not working
AV-8B: same as F-18C
F-14B: you can change the presets with for the front radio with the panel. There is no frequence or preset shown on the panel or something else. It was working with FlightPanels 4.0.76.7111
A-10C: Is not working at all. You can see the ILS channel but it is the wrong one shown on the panel. No frequency, no manipulation from the panel. 

I´m using DCS Open beta with the latest version. 
Probably the reason for the F-18C was because i didnt updated DCS-bios i guess. 
And with the new version, you need to restart DCS-FP every thime you change the module. You cannot simply just change the profile like before.

If i can help you in any way just let me know. 
I can continue testing, if you wish, own all modules.

**Comment by WarLord211** [comment] 2020-08-09 17:47
which BIOS you use?

**Comment by jdahlblom** [comment] 2020-08-09 17:59
@WarLord211, have you seen the same in those modules apart from F-18C?

**Comment by WarLord211** [comment] 2020-08-09 18:28
F-14 i used on Friday, all worked fine. Can turn manual frequencies for booth radios.
A-10 and F5 i tryed after releaes of last FP worked for me.
Harrier has no programmed radio i think and F-18 is broken longtime

@Kurothas FP restarts automatic after changing the profile to make sure that BIOS is anf FP working properly

**Comment by Kurothas** [comment] 2020-08-10 11:49
> 
> 
> which BIOS you use?

The latest one i guess. Downloaded it from here: https://github.com/DCSFlightpanels/dcs-bios

**Comment by Kurothas** [comment] 2020-08-10 11:51
> @Kurothas FP restarts automatic after changing the profile to make sure that BIOS is anf FP working properly

Yes FP restarts in the current versio. But for me it is not working after the software restarts. I need to close and restart FP again, then its fine.

**Comment by emcek** [comment] 2020-08-11 21:42
Not sure it was the same, but shortly after upgrade to 4.1.12 Ka-50 radios worked weird. When turn COM/NAV/ADF knobs, data or frequencies appear on wrong row or column of LCDs. I want even report it but after restart DCSFP it is back to normal and I'm unable to reproduce.

**Comment by Nick-Thain** [comment] 2021-03-07 00:55
Plus 1 for this issue, but for me it's just the channel changing. Other than that this profile is bloody peeeeeerfect. Would LOVE me some channel changing action to top it all off!
Cheers, Nick

**Comment by jdahlblom** [comment] 2021-03-07 10:10
Hi, and thanks for the donation Nick!
I will investigate the F-18C and at some point release a version with the pre-release merged into base release. Confusing as it is for users.

> 
> 
> Plus 1 for this issue, but for me it's just the channel changing. Other than that this profile is bloody peeeeeerfect. Would LOVE me some channel changing action to top it all off!
> Cheers, Nick

**Comment by jdahlblom** [comment] 2021-03-07 11:47
@Nick-Thain  I have tested the F/A-18C radio. DCSFP 4.2.13 and DCS-BIOS 0.7.39. 
It works for me, please report back. Does yourDCS-BIOS Control Reference Page (CTRL-Ref) work as intended?
https://github.com/DCSFlightpanels/DCSFlightpanels/wiki/Installation

**Comment by Nick-Thain** [comment] 2021-03-07 14:48
You're very welcome mate!
I'm about to head out for an early hike, just wanted to pass on what I
experienced when I tried the above:

   - I updated DCSFP to the latest version using your link.
   - When I fired it up, there were no DCS-Bios options available in the
   modules, only Key Emulation or Key Emulation with SRS.
      - I tried the next-older version and I see the DCS-BIOS modules again.
   -  I tried to follow your Installation guide, but got lost at the
   Ctrl-Ref stage.
      - I have the latest DCS-BIOS installed already.
      - I installed the DCS-BIOS Ctrl-Ref Page per your instructions, and I
      see it under Apps in Chrome.
      - Started a Hornet instant mission in DCS.
      - But I cannot figure out how to 'Open CTRL-Ref  from Apps in
      Chrome'. My Ctrl-Ref app looks like this:
      - [image: image.png]
      - There's no 'Open' I can see.. so I tried clicking on 'background
      ref', and I get this:
      - [image: image.png]
      - Is that what I should see? If so, how do I choose a 'correct module
      in the top drop down box'?
         - Wait - did you mean for us to choose the correct module from
         DCSFP?

Due to the above lack of DCS-BIOS modules in this latest DCSFP I wasn't
able to test the Hornet this morning mate, I'm really looking forward to
testing it later! I have to run now, but a few quick points before I do:

   - I'm running DCS-BIOS hub 0.10.0, I assume that's the right one? I
   think it's the latest.
   - I'm also running the latest DCS-BIOS, loaded it up yesterday.
   - I'm running the Open Beta of DCS.

Given all that, I assume that the latest DCSFP is the right one for me,
right? It works for both Stable and Open Beta?
Thanks Jerker!
Cheers, Nick

**Comment by Nick-Thain** [comment] 2021-03-07 14:50
OH!
In case you didn't see it in 'Issues', any ideas on how I can get NS430
controls for FC3 modules? REALLY would love to control the NS430 with my
Radio Panel knobs!
CHeers mate!
Nick ;)

**Comment by jdahlblom** [comment] 2021-03-07 16:38
@Nick-Thain You are using the wrong DCS-BIOS.
1. Install correct DCS-BIOS
2. Verify DCS-BIOS Control Reference Page (CTRL-Ref)?
https://github.com/DCSFlightpanels/DCSFlightpanels/wiki/Installation
3. Run DCSFP

Get DCS-BIOS from here : https://github.com/DCSFlightpanels/dcs-bios/releases/tag/0.7.39a

That should do it.

**Comment by Nick-Thain** [comment] 2021-03-07 23:59
Hey thanks,
I downloaded 0.7.39a DCS-BIOS, but the latest DCSFP is still not showing
any DCS-BIOS modules:
[image: image.png]

**Comment by jdahlblom** [comment] 2021-03-08 08:53
OK. **Assuming you have CTRL-Ref working for DCS-BIOS**, it looks like you are not pointing DCSFP to where the json files are located. Check that setting. [Options] => [Settings] => [DCS-BIOS] => "DCS-BIOS Settings"
Default setting should do most of the times.
This is where I have mine (stable): C:\Users\<user>\Saved Games\DCS\Scripts\DCS-BIOS\doc\json
My other installation (openbeta) : C:\Users\<user>\Saved Games\DCS.openbeta\Scripts\DCS-BIOS\doc\json

**Comment by Nick-Thain** [comment] 2021-03-08 14:59
Good morning mate,
You were right, DCSFP was not pointing to the right location, but I never
got the error message that I've gotten from prior versions of DCSFP telling
me to update the location, so I assumed it was right.. my bad. Corrected
the location, and the DCS-BIOS modules are there now, and, even better, the
F/A-18C Channels are changing. Thanks!

With respect to the NS430/FC3:

   - I spoke with BadCRC as you recommended, and he only flyers rotary, so
   he couldn't help me.
   - I think the only way I can control the NS430 with FC3 modules would be
   if you were to re-add the NS430 module as a standalone module in DCSFP.
   - I know from reading the forum that you had this in the early days,
   then you integrated NS430 into the other modules (which is a great solution
   for all those modules!).
   - *Would you be able to re-add the NS430 as a stand alone module AS WELL
   as having it still be integrated into the other modules?*
   - If this can't be done, I'll understand and just use it with the
   non-FC3 modules, but I had to ask ;)

Also:

   - Is there a way to enhance/tweak the pre-programmed PZ69/Radio Panels
   in the DCS-BIOS modules? Or would I have to create a generic radio profile..
   - I'm not sure if I have Ctrl-Ref working, is this what it should look
   like?:
   - [image: image.png]

Thanks again mate!
Nick

**Comment by Nick-Thain** [comment] 2021-03-10 07:01
Just checking back on this,
Would it be possible/not a pain in the ass to add a separate module for NS430?
Thanks!
Nick

On Mar 8, 2021, at 06:59, Nick Thain <nick.thain@gmail.com> wrote:

﻿
Good morning mate,
You were right, DCSFP was not pointing to the right location, but I never got the error message that I've gotten from prior versions of DCSFP telling me to update the location, so I assumed it was right.. my bad. Corrected the location, and the DCS-BIOS modules are there now, and, even better, the F/A-18C Channels are changing. Thanks!

With respect to the NS430/FC3:
I spoke with BadCRC as you recommended, and he only flyers rotary, so he couldn't help me.
I think the only way I can control the NS430 with FC3 modules would be if you were to re-add the NS430 module as a standalone module in DCSFP.
I know from reading the forum that you had this in the early days, then you integrated NS430 into the other modules (which is a great solution for all those modules!).
Would you be able to re-add the NS430 as a stand alone module AS WELL as having it still be integrated into the other modules?
If this can't be done, I'll understand and just use it with the non-FC3 modules, but I had to ask ;) 
Also:
Is there a way to enhance/tweak the pre-programmed PZ69/Radio Panels in the DCS-BIOS modules? Or would I have to create a generic radio profile..
I'm not sure if I have Ctrl-Ref working, is this what it should look like?:
<image.png>

Thanks again mate!
Nick

**Closed as completed** 2021-03-18 17:18 UTC
Labels: Missing Module
