### ISSUE TITLE
Name of actions not saved

### ISSUE THREAD

**Issue by BSDBaDCrC** [DCS-Skunkworks/DCSFlightpanels#78] opened 2020-06-07 18:15 UTC
When creating an action and leaving the name field empty, DCSFP will by default name the action DCS-BIOS (assuming you chose DCS-BIOS for the action). But if you are trying to name the action, the name will not be saved and the action will still be named DCS-BIOS.

**Comment by jdahlblom** [comment] 2020-06-09 15:02
OK will check.

**Comment by jdahlblom** [comment] 2020-06-13 16:31
On any specific panel?

**Comment by WarLord211** [comment] 2020-07-11 10:18
Duplicate of #83

**Comment by WarLord211** [comment] 2020-07-31 11:31
its solved in 4.1.12

**Closed as completed by WarLord211** 2020-07-31 11:31 UTC
Labels: duplicate
