### ISSUE TITLE
F18 radio panel issue

### ISSUE THREAD

**Issue by epalzeolithe** [DCS-Skunkworks/DCSFlightpanels#106] opened 2021-02-15 10:28 UTC
Hi you did a real good job

well i've got an issue on F18 module, radios/channels are displayed well, but the knobs dont change anything (volume or channel)

is there a fix ?

Thanks !

**Comment by WarLord211** [comment] 2021-02-15 16:03
Bios version?

**Comment by jdahlblom** [comment] 2021-02-16 07:27
https://github.com/DCSFlightpanels/DCSFlightpanels/wiki/Creating-Github-Issue(s)-(bug-reports---feature-requests)

**Comment by WarLord211** [comment] 2021-03-07 07:46
Duplicate of #75

**Comment by WarLord211** [comment] 2021-03-07 07:49
Have you tryed the prerelease  4.2.10 ?

**Closed as completed** 2021-03-18 16:17 UTC
Labels: duplicate
